### ISSUE TITLE
Error: ENOENT: no such file or directory, scandir

### ISSUE THREAD

**Issue by 68267a** [guysoft/MagicMirrorOS#36]
`docker logs mm`

```
Ready to go! Please point your browser to: http://0.0.0.0:8080
[11.05.2021 19:51.46.736] [INFO]  Checking git for module: mmpm
[11.05.2021 19:51.46.738] [INFO]  Checking git for module: MMM-BackgroundSlideshow
[11.05.2021 19:51.46.860] [INFO]  Checking git for module: calendar_monthly
[11.05.2021 19:51.46.878] [INFO]  Checking git for module: MMM-Dad-Jokes
[11.05.2021 19:51.46.933] [ERROR] Whoops! There was an uncaught exception...
[11.05.2021 19:51.46.942] [ERROR] Error: ENOENT: no such file or directory, scandir 'modules/MMM-BackgroundSlideshow/wallpapers/SFW/'
    at Object.readdirSync (fs.js:1021:3)
    at Class.getFiles (/opt/magic_mirror/modules/MMM-BackgroundSlideshow/node_helper.js:130:47)
    at Class.gatherImageList (/opt/magic_mirror/modules/MMM-BackgroundSlideshow/node_helper.js:109:12)
    at Timeout._onTimeout (/opt/magic_mirror/modules/MMM-BackgroundSlideshow/node_helper.js:175:14)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7) {
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: 'modules/MMM-BackgroundSlideshow/wallpapers/SFW/'
}
[11.05.2021 19:51.46.943] [ERROR] MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
[11.05.2021 19:51.46.945] [ERROR] If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
[11.05.2021 19:51.47.966] [ERROR] Failed to fetch git data for MMM-Dad-Jokes: Error: block timeout reached
[11.05.2021 19:51.49.052] [ERROR] Failed to fetch git data for calendar_monthly: Error: block timeout reached
[11.05.2021 19:51.50.137] [ERROR] Failed to fetch git data for MMM-BackgroundSlideshow: Error: block timeout reached
[11.05.2021 19:51.51.216] [ERROR] Failed to fetch git data for default: Error: block timeout reached
[11.05.2021 19:59.44.047] [ERROR] Whoops! There was an uncaught exception...
[11.05.2021 19:59.44.050] [ERROR] Error: ENOENT: no such file or directory, scandir 'modules/MMM-BackgroundSlideshow/wallpapers/SFW/'
    at Object.readdirSync (fs.js:1021:3)
    at Class.getFiles (/opt/magic_mirror/modules/MMM-BackgroundSlideshow/node_helper.js:130:47)
    at Class.gatherImageList (/opt/magic_mirror/modules/MMM-BackgroundSlideshow/node_helper.js:109:12)
    at Timeout._onTimeout (/opt/magic_mirror/modules/MMM-BackgroundSlideshow/node_helper.js:175:14)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7) {
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: 'modules/MMM-BackgroundSlideshow/wallpapers/SFW/'
}
[11.05.2021 19:59.44.052] [ERROR] MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
[11.05.2021 19:59.44.054] [ERROR] If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
[11.05.2021 20:01.52.300] [ERROR] Failed to fetch git data for MMM-Dad-Jokes: Error: block timeout reached
[11.05.2021 20:01.53.394] [ERROR] Failed to fetch git data for calendar_monthly: Error: block timeout reached
[11.05.2021 20:01.54.482] [ERROR] Failed to fetch git data for MMM-BackgroundSlideshow: Error: block timeout reached
[11.05.2021 20:01.55.562] [ERROR] Failed to fetch git data for default: Error: block timeout reached
```

Is this a bad docker mount or do I need to `ln -s /opt/magic_mirror ~/magicmirror/mounts`?

**Comment by 68267a** [comment]
The docker container constantly restarts if MMM-AnyList is enabled. It can't find module `anylist`, so I'm thinking it might be related.

**Comment by khassel** [comment]
> Is this a bad docker mount or do I need to ln -s /opt/magic_mirror ~/magicmirror/mounts?

No. `/opt/magic_mirror` is inside the container, `~/magicmirror/mounts` is on the host.

> `[11.05.2021 19:59.44.050] [ERROR] Error: ENOENT: no such file or directory, scandir 'modules/MMM-BackgroundSlideshow/wallpapers/SFW/'`

This means something is wrong with the setup of `MMM-BackgroundSlideshow`. Maybe not installed correctly or the module configuration is messed up. How did you install your modules? With mmpm?

> The docker container constantly restarts if MMM-AnyList is enabled. It can't find module anylist, so I'm thinking it might be related.

Same thing, maybe not installed correctly or the module configuration is messed up.

**Comment by 68267a** [comment]
Fixed, I had created a symlink in `~/magicmirror/modules` instead of `~/magicmirror/mounts/modules`.
